### ISSUE TITLE
Key:: Value 识别

### ISSUE THREAD

**Issue by KrDw9ec4** [KrDw9ec4/Python_Script#6]
在 flomo 记录时使用 `Key:: Value` 的形式，等汇总时将其更改格式放入 YAML 区。

**Comment by KrDw9ec4** [comment]
比如记录事件涉及朋友时，可以用 `FRM:: 张三，李四，王五` 的形式在 flomo 记录，然后汇总时变成

```yaml
---
Flomo: 2023-09-16 23:41:32
FRM: 
  - 张三
  - 李四
  - 王五
---
```
---
FRM:: Friend Relationship Management
